// LICENSE : MIT
"use strict";

export default {
    "LOAD_ARTICLE": "LOAD_ARTICLE",
    "MOVE_TO_NEXT": "MOVE_TO_NEXT",
    "MOVE_TO_PREV": "MOVE_TO_PREV",
    "MOVE_TO_INDEX": "MOVE_TO_INDEX",
    "REMOVE_ITEM_AT_INDEX": "REMOVE_ITEM_AT_INDEX"
}